# Turns the compiled shader blobs into a C++ header, so the binary carries
# them and there is no install path to get wrong.
#
# At configure time and with nothing but CMake: file(READ ... HEX) is
# enough, and the alternative is a build-time dependency on a hex dumper
# for three kilobytes of data.
#
# The blobs themselves are committed; see tools/shaders/build-shaders.sh.

function(abuse_embed_shaders out_header)
    set(body "// Generated by cmake/EmbedShaders.cmake. Do not edit.\n")
    string(APPEND body "//\n")
    string(APPEND body "// The SDL_GPU shaders, compiled to SPIR-V and built into the\n")
    string(APPEND body "// binary. Sources and blobs are in src/render/gpu/.\n\n")
    string(APPEND body "#ifndef ABUSE_RENDER_GPU_SHADERS_H_\n")
    string(APPEND body "#define ABUSE_RENDER_GPU_SHADERS_H_\n\n")
    string(APPEND body "#include <stdint.h>\n\n")
    string(APPEND body "namespace abuse::render::gpu {\n\n")

    foreach(name IN LISTS ARGN)
        set(path "${CMAKE_CURRENT_SOURCE_DIR}/render/gpu/${name}.spv")
        if(NOT EXISTS "${path}")
            message(FATAL_ERROR "missing shader blob ${path}; run tools/shaders/build-shaders.sh")
        endif()
        file(READ "${path}" hex HEX)
        string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
        string(REGEX REPLACE "," "" trailing "${name}")
        string(REPLACE "." "_" symbol "${name}")

        string(APPEND body "inline uint8_t const k_${symbol}[] = {\n")
        # Sixteen bytes a line, which is five characters each.
        string(REGEX REPLACE "(.{80})" "\\1\n" wrapped "${bytes}")
        string(APPEND body "${wrapped}\n};\n\n")
    endforeach()

    string(APPEND body "}\n\n#endif\n")
    file(WRITE "${out_header}" "${body}")
endfunction()
